### ISSUE TITLE
Version 0.2 not starting on M1 Pro

### ISSUE THREAD

**Issue by La-te** [Chainfire/UselethMiner#5]
I'm having MacBook Pro 14" 2021 M1 Pro 8 cores. I just tried the latest install and I'm getting the following error. Is this a dependency issue somewhere?

$ /usr/local/uselethminer/uselethminer

Traceback (most recent call last):
  File "/usr/local/uselethminer/uselethminer.py", line 13, in <module>
  File "/usr/local/uselethminer/controller.py", line 10, in <module controller>
  File "/usr/local/uselethminer/stratum.py", line 6, in <module stratum>
  File "/usr/local/uselethminer/jsonrpc.py", line 8, in <module jsonrpc>
  File "/usr/local/uselethminer/jsonrpccrypt.py", line 8, in <module jsonrpccrypt>
  File "/usr/local/uselethminer/cryptography/hazmat/backends/__init__.py", line 9, in default_backend
  File "/usr/local/uselethminer/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module cryptography.hazmat.backends.openssl>
  File "/usr/local/uselethminer/cryptography/hazmat/backends/openssl/backend.py", line 64, in <module cryptography.hazmat.backends.openssl.backend>
  File "/usr/local/uselethminer/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module cryptography.hazmat.bindings.openssl.binding>
ImportError: dlopen(/usr/local/uselethminer/cryptography/hazmat/bindings/_openssl.so, 0x0002): Library not loaded: /opt/homebrew/Cellar/openssl@3/3.0.1/lib/libcrypto.3.dylib
  Referenced from: /usr/local/uselethminer/libssl.3.dylib
  Reason: tried: '/opt/homebrew/Cellar/openssl@3/3.0.1/lib/libcrypto.3.dylib' (no such file), '/usr/lib/libcrypto.3.dylib' (no such file)

**Comment by jonny7737** [comment]
brew reinstall openssl
fix this problem on my OG M1 mini.

**Comment by La-te** [comment]
> brew reinstall openssl fix this problem on my OG M1 mini.

For me it would mean installing brew in the first place. I didn't notice that would be a requirement.

**Comment by Chainfire** [comment]
Hmm interesting. It should actually *not* be a requirement, and it wasn't in 0.1. I'm not sure why it is now.

**Comment by Chainfire** [comment]
Please try v0.22 , should solve the problem.

**Comment by La-te** [comment]
I didn't install homebrew. v0.22 seems to work. Thank you.
